### ISSUE TITLE
[Suggestion/Extension] How to make it screen independent.

### ISSUE THREAD

**Issue by kennyeni** [velos/SectionedGrid#1]
Hi,

I found this library very helpful, I changed it a little bit so I decided to share my findings if anyone is interested.

There's a handy library (https://github.com/Knickedi/android-toolbox) that includes a method to convert from dipToPixels, so if we have a static size "item" we can make something like this:

``` java
colCount = SCREEN_WIDTH / AndroidUtils.dipToPixel(activity.getBaseContext(), FIXED_WIDTH);
```

Then in the row xml just make a lot of includes of the item xml (as many as you want, this will set the maximum elements a row can show)

The result of these changes is that the layout will adapt to any screen width, the view item will not change relative appearance (if you make a square it will remain a square), and all items will display in a predictable way across different platforms.

If this helps someone please let me know :)

**Comment by cirion** [comment]
I'm glad to hear that this library was helpful! We've been pleased to see how many projects it's been used in.

I like the suggestion you make. The current implementation will adapt to different screen widths by varying item widths, but adapting by varying the number of items seems like a reasonable approach, particularly if your items contain images. I'll look into adding this as an alternate mode for SectionableAdapter.

Feel free to send a pull request, otherwise I can make the necessary changes myself.

**Comment by cirion** [comment]
This has been implemented. SectionableAdapter now takes a new optional argument, MODE_VARY_COUNT, to switch the resizing mode. It will automatically recalculate the number of columns supportable within the grid based on the available width; it's not necessary to specify the screen width.

Existing layouts should be fairly easy to adapt to the new system. The most important change is to remove any layout_weight on the grid item. The grid item layout_width will be used to calculate the number of columns. As kennyeni noted, you will also need to provide a sufficient number of grid items within your row. The "bookcase" sample activity has been updated with an example of using the new system.
